project:
  type: website
  output-dir: docs

website:
  title: "Jake Barnabe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
    right:
      - icon: github
        href: https://github.com/jbarns14
      - icon: linkedin
        href: https://www.linkedin.com/in/jake-barnabe/
      - icon: envelope-fill
        href: mailto:jake.barnabe@queensu.ca
    logo: images/Jake.gif
    logo-alt: "Jake Barnabe's Personal Website"
    title: false
    background: "#000000"
    foreground: "#E6E6DD"
    collapse-below: lg

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    includes:
      in-header: styles.css



